apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hawall
  template:
    metadata:
      labels:
        app: hawall
    spec:
      initContainers:
      - name: frontend-files
        image: aramk0/front_end
        command:
        - sh
        - -c
        - |
          mkdir -p shared/templates shared/static
          cp -r /app/templates/* /shared/templates/
          cp -r /app/static/* /shared/static/
          echo "front-end files copied"

        volumeMounts:
        - name: frontend-files
          mountPath: /shared

      containers:
      - name: backend
        image: aramk0/back_end
        ports:
        - containerPort: 8000


        volumeMounts:
        - name: frontend-files
          mountPath: /app/frontend
        - name: secret-volume
          # this is the path INSIDE THE CONTAINER at which the secret must be found check the api files
          mountPath: /etc/secrets

        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8000


      volumes:
      - name: frontend-files
        emptyDir: {}
      - name: secret-volume
        secret:
          secretName: my-secret
